let express=require("express")
const { reg, login } = require("../controlers/usercon")
const { addpost, getall, getbycat, postsbyme, getposts, updposts, addlike, adddlike } = require("../controlers/postcon")
let rt=new express.Router()
rt.post("/reg",reg)
rt.post("/login",login)
rt.post("/add",addpost)
rt.get("/",getall)
rt.get("/posts/:cat",getbycat)
rt.get("/postsbyme/:uid",postsbyme)
rt.get("/admin",getposts)
rt.put("/updpost",updposts)
rt.post("/addlike",addlike)
rt.post("/adddlike",adddlike)
module.exports=rt